stages:
  - test
  - build
  - deploy

default:
  image: python:3.8-alpine
  before_script:
    - pip install -r requirements.txt

"Run test":
  stage: test
  script:
    - pytest -v

"Build image":
  stage: build
  image: docker:20.10.22
  services:
    - docker:20.10.22-dind
  script:
    - docker build -t annahri/ssl-tools:1.0 .

"Deploy django":
  stage: deploy
  script:
    - echo "Deployment"
    - docker images
