- name: NGINX - Making the app config file
  become: true
  ansible.builtin.template:
    src: templates/nginx.j2
    dest: /etc/nginx/conf.d/ssl-tools.conf
    mode: 0644

- name: NGINX - Disable default config
  become: true
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default
    state: absent

- name: NGINX - Making sure nginx service is running
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started

- name: NGINX - Testing the app config
  become: true
  ansible.builtin.command: nginx -t
  register: nginx_test
  changed_when: false

- name: NGINX - Enabling the app config
  when: nginx_test.rc == 0
  become: true
  ansible.builtin.command: nginx -s reload
