- name: Add deadsnakes PPA (Ubuntu)
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:deadsnakes/ppa'

- name: Update Packages (Ubuntu)
  when: ansible_facts['distribution'] == "Ubuntu"
  ansible.builtin.apt: update_cache=yes

- name: Install Python {{ python_version }} (Ubuntu)
  when: ansible_facts['distribution'] == 'Ubuntu'
  ansible.builtin.apt:
    name:
      - python{{ python_version }}
      - python{{ python_version }}-dev
      - python{{ python_version }}-distutils
    state: present
  become: true

- name: Install Python {{ python_version }} (Rocky)
  when: ansible_facts['distribution'] == 'Rocky'
  ansible.builtin.yum: name=python{{ python_version | string | split('.') | join('') }} state=present
  become: true
