- name: Check and Install Python {{ python_version }} if it doesn't exist yet
  block:
    - name: Make sure Python {{ python_version }} is present # noqa command-instead-of-shell
      ansible.builtin.shell: command -v python{{ python_version }}
      register: pythonver_exists
      changed_when: pythonver_exists.rc != 0
      failed_when: false

    - include_tasks: install_python.yaml
      when: pythonver_exists.changed

    - name: Check if PIP is present # noqa command-instead-of-shell
      ansible.builtin.shell: command -v pip
      register: pip_installed
      failed_when: false
      changed_when: pip_installed.rc != 0

    - name: Getting get-pip.py # noqa no-handler
      when: pip_installed.changed
      ansible.builtin.get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py
        mode: 0400

    - name: Installing PIP
      when: pip_installed.rc != 0
      ansible.builtin.command: python{{ python_version }} /tmp/get-pip.py

    - name: Install Pipenv
      ansible.builtin.pip:
        name: pipenv
        executable: pip3

- name: Install NGINX (Ubuntu)
  when: ansible_facts['distribution'] == "Ubuntu"
  ansible.builtin.apt: name=nginx state=present

- name: Install NGINX (Rocky)
  when: ansible_facts['distribution'] == "Rocky"
  ansible.builtin.dnf: name=nginx state=present
