---
- hosts: all
  become: true
  gather_facts: true
  vars:
    python_version: 3.8
    app_path: /srv/apps/ssl-tools/
    app_port: 8700
    domain_name: "{{ lookup('ansible.builtin.env', 'DOMAIN_NAME') }}"
    envs:
      - "DEBUG={{ lookup('ansible.builtin.env', 'DEBUG') }}"
      - "ALLOWED_HOSTS={{ lookup('ansible.builtin.env', 'DOMAIN_NAME') }},127.0.0.1"
      - "SECRET_KEY={{ lookup('ansible.builtin.env', 'SECRET_KEY') }}"
      - "CSRF_TRUSTED_ORIGINS=https://{{ lookup('ansible.builtin.env', 'DOMAIN_NAME') }}"

  tasks:
    - name: Create apps user
      ansible.builtin.user:
        name: apps
        comment: Apps user

    - include_tasks: tasks/packages.yaml
    - include_tasks: tasks/deploy.yaml
    - include_tasks: tasks/tests.yaml
